### ISSUE TITLE
Missing Evince requirement

### ISSUE THREAD

**Issue by jbriales** [brpaz/hawkeye#3]
Hi,
Just a heads up, even if Evince is installed, it may be necessary to install: `sudo apt-get install gir1.2-evince-3.0`
Otherwise I would get the error: "Namespace EvinceView not available"
Quite simple, yet I was not familiar with the gi repository and it was difficult to find this was the missing package to be able to use EvinceView!
It might be good to list this dependence in the requirements :)

**Comment by brpaz** [comment]
Thanks for your feedback. I will add that information to the README. ;)
